version: '2'
.catalog:
  name: "tempeureka"
  version: "v0.0.1"
  description: "public service for tempeureka."
  uuid: tempeureka-0
  minimum_rancher_version: v1.0.0
services:
  eureka:
    scale: 1
    start_on_create: true
    labels:
      io.rancher.container.requested_ip: "10.42.1.210"
  config:
    scale: 1
    start_on_create: true
    labels:
      io.rancher.container.requested_ip: "10.42.1.211"
  account:
    scale: 1
    start_on_create: true
    labels:
      io.rancher.container.requested_ip: "10.42.1.212"
  monitor:
    scale: 1
    start_on_create: true
    labels:
      io.rancher.container.requested_ip: "10.42.1.213"
  apigateway:
    scale: 1
    start_on_create: true
    labels:
      io.rancher.container.requested_ip: "10.42.1.214"
