version: '2'
.catalog:
  name: "tempeureka"
  version: "v0.0.1"
  description: "public service for tempeureka."
  uuid: tempeureka-0
  minimum_rancher_version: v1.0.0
services:
  tempeureka:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 1
      response_timeout: 2000
      port: 8800
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
    labels:
      io.rancher.container.requested_ip: "10.42.1.210"
